module.exports = {
  /* Global API */
  '--globalBackground': 'var(--ne-global-background, hsl(0, 0%, 100%))',
  '--globalForeground': 'var(--ne-global-foreground, hsl(0, 0%, 0%))',
  '--rootFontSize': 'var(--ne-root-font-size, 100%)',
  '--bodyFontSize': 'var(--ne-body-font-size, 1.125rem)',
  '--selectionForeground': 'var(--ne-selection-foreground, hsl(0, 0%, 100%))',
  '--selectionBackground': 'var(--ne-selection-background, hsl(233, 64%, 72%))',
  '--outlineWidth': 'var(--ne-outline-width, 2px)',
  '--outlineColor': 'var(--ne-outline-color, hsl(220, 100%, 50%))',

  /* Typography */
  '--basicLineHeight': 'var(--ne-basic-line-height, 1.5)',
  '--headingsScale': 'var(--ne-headings-scale, 1.25)',
  '--quoteFontSize': 'var(--ne-quote-font-size, 2rem)',
  '--citeForeground': 'var(--ne-cite-foreground, hsl(220, 100%, 50%))',
  '--citeFontSize': 'var(--ne-cite-font-size, 1rem)',
  '--citeStartSign': 'var(--ne-cite-start-sign, "—")',
  '--linksForeground': 'var(--ne-links-foreground, hsl(220, 100%, 50%))',
  '--linksActiveForeground': 'var(--ne-links-active-foreground, hsl(233, 64%, 52%))',
  '--delForeground': 'var(--ne-del-foreground, hsl(337, 74%, 31%))',
  '--delBackground': 'var(--ne-del-background, hsl(0, 100%, 94%))',
  '--insForeground': 'var(--ne-ins-foreground, hsl(161, 98%, 18%))',
  '--insBackground': 'var(--ne-ins-background, hsl(138, 100%, 88%))',
  '--kbdColor': 'var(--ne-kbd-color, hsl(233, 34%, 96%))',
  '--kbdBorderRadius': 'var(--ne-kbd-border-radius, 4px)',
  '--markForeground': 'var(--ne-mark-foreground, hsl(20, 100%, 26%))',
  '--markBackground': 'var(--ne-mark-background, hsl(57, 100%, 60%))',
  '--inlineCodeBorderRadius': 'var(--ne-inline-code-border-radius, 2px)',
  '--inlineCodeBackground': 'var(--ne-inline-code-background, hsl(220, 10%, 95%))',
};
