name: CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v5.0.18
        with:
          tag-prefix: v
      - name: NPM publish if not present
        uses: romainseb/action-npm-publish-if-not-present@0.0.2
        with:
          always-auth: true
